### ISSUE TITLE
Copy: homepage

### ISSUE THREAD

**Issue by jessevondoom** [cashmusic/cashmusic.org#1]
For the new main page.

Latest copy:

MAIN SPACE:
CASH Music is a nonprofit organization that builds open source digital tools for musicians and labels. Our mission is to help educate and empower artists and their fans to foster a more viable and sustainable future for music.

What Wordpress did for bloggers, we're doing for musicians. The goal is to help artists find sustainability and to encourage innovation in the music industry. To that end we built a free and open platform that’s available to all artists, designed in partnership with the artists and labels who are members of our organization.

Some of our members
[member list]

[something about joining mailing list here?]

brought to you in part by:
[sponsors]

SIDE BAR THING:
(This will be universal across the site)
We’re building a free and open platform that gives musicians and labels a no-programming environment for music tech online. You download it, the platform works with your website, integrates with what you’ve got, and plays nice with services like SoundCloud, PayPal, Facebook, Twitter, MailChimp, and more.

See the Demos

Get The Code (Developer preview release. See latest release notes.)

All our code is open-source. Learn More.

**Comment by maggiev23** [comment]
thumbs up
