### ISSUE TITLE
Copy: about

### ISSUE THREAD

**Issue by jessevondoom** [cashmusic/cashmusic.org#4]
From: http://cashmusic.org/about/

This copy is crazy long. There are some reasons for that, but I think we can condense it a ton. Ideally it's a couple more assertive paragraphs, then "Staff" listing:
- Maggie Vail
- Jesse von Doom
- Duke Leto

Followed by the full board list (maybe updated? We should make calls/emails Mon/Tue)

Maybe a link to an FAQ page?

**Comment by maggiev23** [comment]
will work on about stuff after comet blog post and press release rework.  definitely staff and board here.  and link to FAQ for sure.
